---

- name: template torrc
  template: src=torrc dest=/etc/tor/torrc
    owner=root group=root mode=0644
  notify:
  - restart tor

- name: make sure tor is running
  service: name=tor state=running


