---

- name: create tor hidden services parent directory
  file: path={{ tor_hidden_services_parent_dir }} state=directory

- name: create tor hidden services directories
  file: path={{ tor_hidden_services_parent_dir }}/{{ item.dir }}
   state=directory owner=debian-tor
  with_items: tor_hidden_services
