---

- name: install tor project apt signing gpg key
  apt_key: >
    state=present
    data="{{ lookup('file', 'tor-signing-key.pub') }}"

- name: setup tor apt repo
  apt_repository: >
    repo='deb http://deb.torproject.org/torproject.org {{ tor_distribution_release }} main'
    state=present 
    update_cache=yes

- name: setup tor src apt repo
  apt_repository: >
    repo='deb-src http://deb.torproject.org/torproject.org {{ tor_distribution_release }} main'
    state=present 
    update_cache=yes

## in case {{ tor_distribution_release }} is a development branch (ie. the name starts with tor-experimental), the line with the distribution name is also needed to install deb.torproject.org-keyring
- name: get distribution name from tor_distribution_release variable
  shell: python -c "print '{{ tor_distribution_release }}'.split('-')[-1]"
  register: distribution
  when: tor_distribution_release.startswith('tor-experimental')

- name: setup tor apt repo in case tor_distribution_release is a development branch
  apt_repository: >
    repo='deb http://deb.torproject.org/torproject.org {{ distribution.stdout }} main'
    state=present 
    update_cache=yes
  when: tor_distribution_release.startswith('tor-experimental')

- name: install tor keyring and some build dependency packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: ["deb.torproject.org-keyring", "fakeroot", "devscripts"]

- name: apt-get build-dep tor
  command: "apt-get build-dep tor"
  sudo: yes

- name: apt-get source tor
  command: "chdir={{ tor_tor2web_build_dir }} apt-get source tor"
  sudo: yes

- name: get new tor source dir
  command: "chdir={{ tor_tor2web_build_dir }} ls -l tor*"
  register: tor_dir
  sudo: yes

