---

## install
- name: get state of installed tor
  command: which tor
  register: which_tor
  ignore_errors: True

- name: install tor
  include: install_tor.yml
  when: which_tor.rc != 0

- include: install_pip_obfsproxy.yml
  sudo: no
  when: tor_obfsproxy_virtenv is defined


## configure

- include: hidden_services.yml
  when: tor_hidden_services is defined

- include: configure_apt_single.yml


## wait for hidden services
- include: wait_for_hidden_services.yml
  when: tor_wait_for_hidden_services is defined

- include: set_hidden_services_facts.yml
  when: tor_hidden_services is defined
