---

- include: install.yml

- include: install_pip_obfsproxy.yml
  sudo: no
  when: tor_obfsproxy_virtenv is defined

- include: hidden_services.yml
  when: tor_hidden_services is defined

- include: configure.yml

- include: wait_for_hidden_services.yml
  when: tor_wait_for_hidden_services is defined

- include: set_hidden_services_facts.yml
  when: tor_hidden_services is defined



